apiVersion: v1
kind: Template
labels: 
  template: template-name
metadata: 
  annotations: 
    description: "Application template for EAP 6 applications built using STI."
    iconClass: icon-jboss
  name: template-name
objects: 
  - 
    apiVersion: v1
    kind: Namespace
    metadata: 
      labels: ~
      name: test-template-namespace
  - 
    apiVersion: extensions/v1beta1
    kind: Deployment
    metadata: 
      name: "${DEP_NAME}"
      namespace: test-template-namespace
    spec: 
      replicas: 1
      selector: 
        matchLabels: 
          app: sampleapp
      template: 
        metadata: 
          labels: 
            app: sampleapp
        spec: 
          containers: 
            - 
              image: "cddirector/sampleapp:1"
              imagePullPolicy: Always
              name: sampleapp
              ports: 
                - 
                  containerPort: 8080
                  protocol: TCP
parameters: 
  - 
    description: "EAP Release version, e.g. 6.4, etc."
    name: DEP_NAME
    required: true
    value: "test template"
